texto=input("incresa un texto a continuacion: ")
letras=[]
print("\n")
print(texto)
print("\n")
print("\n")
letras.append(input("escribe la primera letra"))
letras.append(input("escribe la segunda letra"))
letras.append(input("escribe la tercera letra"))
print("Listado de letras eleidas")
print(letras)
#ver cuantas veces aparece en el texto las letras que puso
print("\n")
print("CANTIDAD DE LETRAS ELEGIDAS EN TEXTO")
print(f" hay un total de  {texto.count(letras[0])} letras de la primera palabra.\n un total de {texto.count(letras[1])} letras de la palabra 2 \ny un total de {texto.count(letras[2])} letras de la palabra 3")
palabras=texto.split()
print("\n")
print(f"La cantidad de palabras que hay en el texto son {len(palabras)}")
print("\n")
print(f"la primera palabra y la ultima del texto es: {palabras[0]} \n y la ultima es :{palabras[-1]} ")
print("\n")
print("Esta la palabra Python en el texto?? verdadero o falso")
python=("python" in texto)
dic={True:"Si",False:"No"}
print(f'la palabra Python, {dic[python]} se encuentra en el texto')